Add PII data to endpoint
levoai/demo-apps pull request #79
Opened 2022-08-23 20:01 UTC by ricekot

Also update spec from upstream crAPI.

2022-08-23 21:29 UTC, mgiamberardino requested changes
LGTM. Just one change around how Luhn is getting calculated.

2022-08-23 21:29 UTC, mgiamberardino commented on crAPI/services/identity/src/main/java/com/crapi/utils/CreditCardNumberGenerator.java
> +        for (int i = 0; i < number.length(); i++) {
@ricekot For the Luhn algorithm, you need to start sum from the right and duplicate every second digit including the rightmost digit. Starting from the beginning result will be suitable only for odd-length numbers.

2022-08-24 03:49 UTC, buchi-busireddy approved these changes

2022-08-24 04:19 UTC, buchi-busireddy commented
@mgiamberardino Merging this since @ricekot has fixed your comment and we need this for demo setup. Please review again and leave if you have more comments.

2022-08-24 04:19 UTC, merged